# Generated by Django 4.1 on 2022-08-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title_post',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
