# Generated by Django 4.1 on 2022-08-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_posts_title_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
