# Generated by Django 4.1 on 2022-08-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_articles_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
