# Generated by Django 4.1 on 2022-08-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_articles_post_id_posts_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
